# -*- coding: utf-8 -*-
"""
单一数据源：策展约 440 幅各流派名画，生成
  1) 前端 index.html 的 aestheticCollection 数组
  2) 后端 server.py 的 ART_COLLECTION（id, en搜索名, wm文件名/None）
后端代理会按 en 自动在维基搜索解析文件名，无需手核 wm（仅 44 幅旧图保留已知 wm）。
运行: python scripts/gen_art.py
"""
import os, re, io

# 44 幅旧图的已知 Wikimedia 文件名（fast path，避免搜索）
KNOWN_WM = {
    "mona-lisa": "Mona_Lisa,_by_Leonardo_da_Vinci,_from_C2RMF_retouched.jpg",
    "birth-of-venus": "Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg",
    "school-of-athens": "Raffael_058.jpg",
    "sistine-madonna": "Sistine_Madonna_(original)_FXD.jpg",
    "creation-adam": "Michelangelo_-_Creation_of_Adam_(cropped).jpg",
    "arnolfini": "Van_Eyck_-_Arnolfini_Portrait.jpg",
    "garden-delights": "The_Garden_of_earthly_delights.jpg",
    "tower-babel": "Pieter_Bruegel_the_Elder_-_The_Tower_of_Babel_(Vienna)_-_Google_Art_Project_-_edited.jpg",
    "durer-self": "Albrecht_Dürer_-_1500_self-portrait_(High_resolution_and_detail).jpg",
    "melencolia": "Albrecht_Dürer_-_Melencolia_I_-_Google_Art_Project_(427760).jpg",
    "night-watch": "Rembrandt_van_Rijn-De_Nachtwacht-1642.jpg",
    "rembrandt-self": "Rembrandt_van_Rijn_-_Self-Portrait_-_Google_Art_Project.jpg",
    "las-meninas": "Las_Meninas,_by_Diego_Velázquez,_from_Prado_in_Google_Earth.jpg",
    "girl-pearl": "1665_Girl_with_a_Pearl_Earring.jpg",
    "liberty": "Eugène_Delacroix_-_La_liberté_guidant_le_peuple.jpg",
    "wanderer-fog": "Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg",
    "third-may": "El_Tres_de_Mayo,_by_Francisco_de_Goya,_from_Prado_in_Google_Earth.jpg",
    "hay-wain": "John_Constable_The_Hay_Wain.jpg",
    "fighting-temeraire": "The_Fighting_Temeraire,_JMW_Turner,_National_Gallery.jpg",
    "ophelia": "John_Everett_Millais_-_Ophelia_-_Google_Art_Project.jpg",
    "impression-sunrise": "Monet_-_Impression,_Sunrise.jpg",
    "water-lilies": "Claude_Monet_-_Water_Lilies_-_1906,_Ryerson.jpg",
    "starry-night": "Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg",
    "sunflowers": "Vincent_Willem_van_Gogh_127.jpg",
    "moulin-rouge": "Henri_de_Toulouse-Lautrec_-_At_the_Moulin_Rouge_-_Google_Art_Project.jpg",
    "kiss-klimt": "The_Kiss_-_Gustav_Klimt_-_Google_Cultural_Institute.jpg",
    "scream": "Edvard_Munch,_1893,_The_Scream,_oil,_tempera_and_pastel_on_cardboard,_91_x_73_cm,_National_Gallery_of_Norway.jpg",
    "schiele-self": "Egon_Schiele_-_Self-Portrait_with_Lowered_Head_-_Google_Art_Project.jpg",
    "persistence-memory": "The_Persistence_of_Memory.jpg",
    "american-gothic": "Grant_Wood_-_American_Gothic_-_Google_Art_Project.jpg",
    "sleeping-gypsy": "La_Bohémienne_endormie.jpg",
    "mondrian-comp": "Composition-with-red-yellow-and-blue.jpg",
    "black-square": "Malevich.black-square.jpg",
    "whistler-mother": "Whistlers_Mother_high_res.jpg",
    "olympia": "Edouard_Manet_-_Olympia_-_Google_Art_Project_3.jpg",
    "great-wave": "Tsunami_by_hokusai_19th_century.jpg",
    "vitruvian": "Da_Vinci_Vitruve_Luc_Viatour.jpg",
    "libyan-sibyl": "LibyanSibyl_SistineChapel.jpg",
    "anatomical-shoulder": "Leonardo_da_Vinci_-_Anatomical_studies_of_the_shoulder_-_WGA12824.jpg",
    "study-hands": "Leonardo_da_Vinci_-_Study_of_hands_-_WGA12812.jpg",
    "draftsman-nude": "Dürer_-_Zeichner_und_Akt.jpg",
    "woman-toilette": "Degas_-_Woman-At-Her-Toilette-I.jpg",
    "rembrandt-draw": "Rembrandt_van_Rijn,_Self-Portrait_Drawing_at_a_Window,_1648,_NGA_9930.jpg",
    "hokusai-manga": "Manga_Hokusai.jpg",
    "miro-mere-ubu": "Mère Ubu, Joan Miró.jpg",
    "gauguin-tahiti": "Paul_Gauguin_-_Where_Do_We_Come_From_What_Are_We_What_Are_We_Going_To.jpg",
    "klimt-portrait-adele": "Gustav_Klimt_-_Adele_Bloch-Bauer_I.jpg",

}

# (id, 中文名, 英文搜索名, 艺术家, 年代, 流派, 类型)
# 类型: painting / sketch
ART = [
    # ===================== 文艺复兴 (Italian) =====================
    ("mona-lisa", "蒙娜丽莎", "Mona Lisa Leonardo da Vinci", "列奥纳多·达·芬奇", 1503, "文艺复兴", "painting"),
    ("birth-of-venus", "维纳斯的诞生", "The Birth of Venus Botticelli", "桑德罗·波提切利", 1485, "文艺复兴", "painting"),
    ("school-of-athens", "雅典学院", "The School of Athens Raphael", "拉斐尔", 1511, "文艺复兴", "painting"),
    ("sistine-madonna", "西斯廷圣母", "Sistine Madonna Raphael", "拉斐尔", 1512, "文艺复兴", "painting"),
    ("creation-adam", "创造亚当", "The Creation of Adam Michelangelo", "米开朗基罗", 1512, "文艺复兴", "painting"),
    ("last-supper", "最后的晚餐", "The Last Supper Leonardo da Vinci", "列奥纳多·达·芬奇", 1498, "文艺复兴", "painting"),
    ("annunciation-leonardo", "天使报喜", "Annunciation Leonardo da Vinci", "列奥纳多·达·芬奇", 1472, "文艺复兴", "painting"),
    ("primavera", "春", "Primavera Botticelli", "桑德罗·波提切利", 1480, "文艺复兴", "painting"),
    ("venus-of-urbino", "乌尔比诺的维纳斯", "Venus of Urbino Titian", "提香", 1538, "文艺复兴", "painting"),
    ("bacchus-ariadne", "酒神与阿里阿德涅", "Bacchus and Ariadne Titian", "提香", 1523, "文艺复兴", "painting"),
    ("assumption-virgin", "圣母升天", "Assumption of the Virgin Titian", "提香", 1518, "文艺复兴", "painting"),
    ("pesaro-madonna", "佩萨罗圣母", "Pesaro Madonna Raphael", "拉斐尔", 1526, "文艺复兴", "painting"),
    ("pieta-michelangelo", "圣殇", "Pietà Michelangelo", "米开朗基罗", 1499, "文艺复兴", "painting"),
    ("doni-tondo", "多尼圆形画", "Doni Tondo Michelangelo", "米开朗基罗", 1507, "文艺复兴", "painting"),
    ("tempest", "暴风雨", "The Tempest Giorgione", "乔尔乔内", 1508, "文艺复兴", "painting"),
    ("sleeping-venus", "沉睡的维纳斯", "Sleeping Venus Giorgione", "乔尔乔内", 1510, "文艺复兴", "painting"),
    ("flagellation-piero", "鞭笞基督", "The Flagellation of Christ Piero della Francesca", "皮耶罗·德拉·弗朗切斯卡", 1460, "文艺复兴", "painting"),
    ("baptism-christ-piero", "基督受洗", "The Baptism of Christ Piero della Francesca", "皮耶罗·德拉·弗朗切斯卡", 1450, "文艺复兴", "painting"),
    ("ideal-city", "理想城", "The Ideal City Urbino", "匿名", 1480, "文艺复兴", "painting"),
    ("delivery-of-keys", "交钥匙", "The Delivery of the Keys Perugino", "佩鲁吉诺", 1481, "文艺复兴", "painting"),
    ("annunciation-angelico", "天使报喜", "Annunciation Fra Angelico", "弗拉·安杰利科", 1440, "文艺复兴", "painting"),
    ("madonna-meadow", "草地上的圣母", "Madonna of the Meadow Raphael", "拉斐尔", 1506, "文艺复兴", "painting"),
    ("sacred-profane-love", "神圣与世俗之爱", "Sacred and Profane Love Titian", "提香", 1514, "文艺复兴", "painting"),
    ("diana-actaeon", "戴安娜与阿克泰翁", "Diana and Actaeon Titian", "提香", 1556, "文艺复兴", "painting"),
    ("diana-callisto", "戴安娜与卡利斯托", "Diana and Callisto Titian", "提香", 1559, "文艺复兴", "painting"),
    ("flaying-marsyas", "玛耳绪阿斯的剥皮", "The Flaying of Marsyas Titian", "提香", 1570, "文艺复兴", "painting"),
    ("dead-christ-mantegna", "哀悼死去的基督", "Lamentation of Christ Mantegna", "安德烈亚·曼特尼亚", 1480, "文艺复兴", "painting"),
    ("venus-mars", "维纳斯与战神", "Venus and Mars Botticelli", "桑德罗·波提切利", 1483, "文艺复兴", "painting"),
    ("la-bella", "美人", "La Bella Titian", "提香", 1536, "文艺复兴", "painting"),
    ("presentation-virgin-titian", "圣母进殿", "Presentation of the Virgin Titian", "提香", 1538, "文艺复兴", "painting"),
    ("rape-europa-titian", "欧罗巴的掠夺", "The Rape of Europa Titian", "提香", 1562, "文艺复兴", "painting"),
    ("madonna-chair", "椅中圣母", "Madonna of the Chair Raphael", "拉斐尔", 1514, "文艺复兴", "painting"),
    ("transfiguration-raphael", "基督显圣容", "Transfiguration Raphael", "拉斐尔", 1520, "文艺复兴", "painting"),
    ("tribute-money", "纳税银", "The Tribute Money Masaccio", "马萨乔", 1427, "文艺复兴", "painting"),
    ("expulsion-eden", "逐出伊甸园", "The Expulsion from the Garden of Eden Masaccio", "马萨乔", 1427, "文艺复兴", "painting"),
    ("holy-trinity-masaccio", "圣三位一体", "Holy Trinity Masaccio", "马萨乔", 1427, "文艺复兴", "painting"),
    ("annunciation-martini", "天使报喜", "Annunciation Simone Martini", "西蒙内·马丁尼", 1333, "文艺复兴", "painting"),
    ("good-government", "好政府的效果", "Effects of Good Government Lorenzetti", "安布罗焦·洛伦泽蒂", 1340, "文艺复兴", "painting"),
    ("mystic-nativity", "神秘诞生", "Mystic Nativity Botticelli", "桑德罗·波提切利", 1500, "文艺复兴", "painting"),
    ("battle-san-romano", "圣罗马诺之战", "The Battle of San Romano Uccello", "保罗·乌切洛", 1440, "文艺复兴", "painting"),
    ("marriage-virgin", "圣母的婚礼", "Marriage of the Virgin Raphael", "拉斐尔", 1504, "文艺复兴", "painting"),
    ("parnassus", "帕纳塞斯山", "Parnassus Raphael", "拉斐尔", 1511, "文艺复兴", "painting"),
    ("disputation", "圣礼之争", "Disputation of the Holy Sacrament Raphael", "拉斐尔", 1510, "文艺复兴", "painting"),
    ("castiglione", "巴尔达萨雷·卡斯蒂廖内肖像", "Portrait of Baldassare Castiglione Raphael", "拉斐尔", 1519, "文艺复兴", "painting"),
    ("fornarina", "福尔纳丽娜", "La Fornarina Raphael", "拉斐尔", 1518, "文艺复兴", "painting"),
    ("virgin-rocks", "岩间圣母", "Virgin of the Rocks Leonardo da Vinci", "列奥纳多·达·芬奇", 1486, "文艺复兴", "painting"),
    ("st-john-leonardo", "施洗者圣约翰", "St. John the Baptist Leonardo da Vinci", "列奥纳多·达·芬奇", 1513, "文艺复兴", "painting"),
    ("ginevra", "吉内薇拉·德·本奇", "Ginevra de' Benci Leonardo da Vinci", "列奥纳多·达·芬奇", 1474, "文艺复兴", "painting"),
    ("primavera-done", "春（细节）", "La Primavera Botticelli", "桑德罗·波提切利", 1480, "文艺复兴", "painting"),
    ("venus-courtesans", "维纳斯与武尔坎努斯", "Venus and Vulcan Botticelli", "桑德罗·波提切利", 1485, "文艺复兴", "painting"),
    ("cappella", "签署厅天顶", "Stanza della Segnatura Raphael", "拉斐尔", 1511, "文艺复兴", "painting"),
    ("pieta-van-der-weyden", "下十字架", "The Descent from the Cross van der Weyden", "罗希尔·范·德·维登", 1435, "文艺复兴", "painting"),

    # ===================== 北方文艺复兴 =====================
    ("arnolfini", "阿尔诺非尼夫妇肖像", "Arnolfini Portrait Jan van Eyck", "扬·凡·艾克", 1434, "北方文艺复兴", "painting"),
    ("garden-delights", "人间乐园", "The Garden of Earthly Delights Bosch", "希罗尼穆斯·博斯", 1505, "北方文艺复兴", "painting"),
    ("tower-babel", "巴别塔", "The Tower of Babel Bruegel", "老彼得·勃鲁盖尔", 1563, "北方文艺复兴", "painting"),
    ("durer-self", "自画像", "Albrecht Dürer self-portrait 1500", "阿尔布雷希特·丢勒", 1500, "北方文艺复兴", "painting"),
    ("melencolia", "忧郁症 I", "Melencolia I Dürer", "阿尔布雷希特·丢勒", 1514, "北方文艺复兴", "painting"),
    ("draftsman-nude", "素描者画裸体", "Dürer draftsman drawing nude", "阿尔布雷希特·丢勒", 1538, "北方文艺复兴", "sketch"),
    ("hunters-snow", "雪中猎人", "The Hunters in the Snow Bruegel", "老彼得·勃鲁盖尔", 1565, "北方文艺复兴", "painting"),
    ("peasant-wedding", "农民婚礼", "The Peasant Wedding Bruegel", "老彼得·勃鲁盖尔", 1567, "北方文艺复兴", "painting"),
    ("tower-babel2", "巴别塔（小）", "The Tower of Babel Rotterdam Bruegel", "老彼得·勃鲁盖尔", 1563, "北方文艺复兴", "painting"),
    ("dead-bird", "死鸟", "A Dead Bird Dürer", "阿尔布雷希特·丢勒", 1500, "北方文艺复兴", "painting"),
    ("four-apostles", "四使徒", "The Four Apostles Dürer", "阿尔布雷希特·丢勒", 1526, "北方文艺复兴", "painting"),
    ("adam-eve-durer", "亚当与夏娃", "Adam and Eve Dürer", "阿尔布雷希特·丢勒", 1507, "北方文艺复兴", "painting"),
    ("arnolfini-detail", "阿尔诺非尼肖像", "Portrait of Giovanni Arnolfini van Eyck", "扬·凡·艾克", 1434, "北方文艺复兴", "painting"),
    ("lucca-madonna", "卢卡圣母", "Lucca Madonna van Eyck", "扬·凡·艾克", 1437, "北方文艺复兴", "painting"),
    ("ghent-altarpiece", "根特祭坛画", "The Ghent Altarpiece van Eyck", "扬·凡·艾克", 1432, "北方文艺复兴", "painting"),
    ("windmill", "有风车的风景", "The Windmill at Wijk du Gardin", "扬·范·戈因", 1640, "北方文艺复兴", "painting"),
    ("massacre-innocents", "无辜者的大屠杀", "The Massacre of the Innocents Bruegel", "老彼得·勃鲁盖尔", 1565, "北方文艺复兴", "painting"),
    ("fall-icarus", "伊卡洛斯的坠落", "Landscape with the Fall of Icarus Bruegel", "老彼得·勃鲁盖尔", 1558, "北方文艺复兴", "painting"),
    ("haywain-bruegel", "干草车", "The Haywain Bruegel", "老彼得·勃鲁盖尔", 1565, "北方文艺复兴", "painting"),
    ("census-bethlehem", "伯利恒户口调查", "The Census at Bethlehem Bruegel", "老彼得·勃鲁盖尔", 1566, "北方文艺复兴", "painting"),
    ("madonna-cannon", "班纳主教圣母", "The Canon's Virgin Holbein", "小汉斯·霍尔拜因", 1523, "北方文艺复兴", "painting"),
    ("ambassadors", "大使们", "The Ambassadors Holbein", "小汉斯·霍尔拜因", 1533, "北方文艺复兴", "painting"),

    # ===================== 巴洛克 =====================
    ("night-watch", "夜巡", "The Night Watch Rembrandt", "伦勃朗", 1642, "巴洛克", "painting"),
    ("rembrandt-self", "自画像", "Rembrandt self-portrait", "伦勃朗", 1640, "巴洛克", "painting"),
    ("las-meninas", "宫娥", "Las Meninas Velázquez", "迭戈·委拉斯开兹", 1656, "巴洛克", "painting"),
    ("rembrandt-draw", "窗边自画像（素描）", "Rembrandt self-portrait drawing at a window", "伦勃朗", 1648, "巴洛克", "sketch"),
    ("call-girl", "夜巡（细节）", "The Night Watch detail Rembrandt", "伦勃朗", 1642, "巴洛克", "painting"),
    ("anatomy-lesson", "杜普教授的解剖课", "The Anatomy Lesson of Dr. Nicolaes Tulp Rembrandt", "伦勃朗", 1632, "巴洛克", "painting"),
    ("syndics", "纺织公会理事", "The Syndics of the Drapers' Guild Rembrandt", "伦勃朗", 1662, "巴洛克", "painting"),
    ("bethlehem-rembrandt", "伯利恒的婴儿屠杀", "The Massacre of the Innocents Rembrandt", "伦勃朗", 1635, "巴洛克", "painting"),
    ("return-prodigal", "浪子回头", "The Return of the Prodigal Son Rembrandt", "伦勃朗", 1669, "巴洛克", "painting"),
    ("blinding-samson", "参孙被弄瞎", "The Blinding of Samson Rembrandt", "伦勃朗", 1636, "巴洛克", "painting"),
    ("jewish-bride", "犹太新娘", "The Jewish Bride Rembrandt", "伦勃朗", 1667, "巴洛克", "painting"),
    ("las-meninas2", "宫娥（镜像）", "Las Meninas detail Velázquez", "迭戈·委拉斯开兹", 1656, "巴洛克", "painting"),
    ("surrender-breda", "布雷达的投降", "The Surrender of Breda Velázquez", "迭戈·委拉斯开兹", 1635, "巴洛克", "painting"),
    ("venus-mirror", "镜前的维纳斯", "Venus at her Mirror Velázquez", "迭戈·委拉斯开兹", 1651, "巴洛克", "painting"),
    ("waterseller", "喝水者", "The Waterseller of Seville Velázquez", "迭戈·委拉斯开兹", 1620, "巴洛克", "painting"),
    ("judith-beheading", "朱迪斯斩首荷罗孚尼", "Judith Beheading Holofernes Artemisia", "阿特米西娅·真蒂莱斯基", 1614, "巴洛克", "painting"),
    ("self-artemisia", "自画像（弹鲁特琴）", "Self-Portrait as the Allegory of Painting Artemisia", "阿特米西娅·真蒂莱斯基", 1638, "巴洛克", "painting"),
    ("callisto", "卡利斯托的捕获", "The Capture of Callisto Titian", "提香", 1559, "巴洛克", "painting"),
    ("caravaggio-bacchus", "酒神巴克斯", "Bacchus Caravaggio", "卡拉瓦乔", 1596, "巴洛克", "painting"),
    ("caravaggio-supper", "以马忤斯的晚餐", "Supper at Emmaus Caravaggio", "卡拉瓦乔", 1601, "巴洛克", "painting"),
    ("caravaggio-calling", "圣马太蒙召", "The Calling of St Matthew Caravaggio", "卡拉瓦乔", 1600, "巴洛克", "painting"),
    ("caravaggio-medusa", "美杜莎", "Medusa Caravaggio", "卡拉瓦乔", 1597, "巴洛克", "painting"),
    ("caravaggio-david", "大卫与歌利亚", "David with the Head of Goliath Caravaggio", "卡拉瓦乔", 1610, "巴洛克", "painting"),
    ("rubens-descent", "下十字架", "The Descent from the Cross Rubens", "彼得·保罗·鲁本斯", 1612, "巴洛克", "painting"),
    ("rubens-kermis", "乡村舞会", "The Village Fête Rubens", "彼得·保罗·鲁本斯", 1635, "巴洛克", "painting"),
    ("rubens-helene", "海伦·芙尔曼与儿女", "Helene Fourment with Children Rubens", "彼得·保罗·鲁本斯", 1636, "巴洛克", "painting"),
    ("rubens-leucippus", "劫夺留西帕斯的女儿", "The Rape of the Daughters of Leucippus Rubens", "彼得·保罗·鲁本斯", 1618, "巴洛克", "painting"),
    ("rubens-self", "自画像", "Self-portrait Rubens", "彼得·保罗·鲁本斯", 1623, "巴洛克", "painting"),
    ("judith-rubens", "朱迪斯与荷罗孚尼的头", "Judith with the Head of Holofernes Rubens", "彼得·保罗·鲁本斯", 1610, "巴洛克", "painting"),
    ("teniers-fair", "乡村集市", "Village Fair Teniers", "大卫·特尼尔斯", 1650, "巴洛克", "painting"),
    ("velazquez-infanta", "穿裙装的小公主", "Infanta Margarita Teresa Velázquez", "迭戈·委拉斯开兹", 1659, "巴洛克", "painting"),
    ("murillo-helen", "圣母无染原罪", "Immaculate Conception Murillo", "巴托洛梅·埃斯特万·穆里略", 1678, "巴洛克", "painting"),
    ("preterite", "阿波罗与达芙妮", "Apollo and Daphne Bernini", "济安·洛伦佐·贝尼尼", 1625, "巴洛克", "painting"),
    ("ecstasy-teresa", "圣特雷莎的沉迷", "Ecstasy of Saint Teresa Bernini", "济安·洛伦佐·贝尼尼", 1651, "巴洛克", "painting"),
    ("las-meninas3", "纺纱女", "The Spinners Velázquez", "迭戈·委拉斯开兹", 1657, "巴洛克", "painting"),
    ("caravaggio-fruit", "水果篮", "Basket of Fruit Caravaggio", "卡拉瓦乔", 1599, "巴洛克", "painting"),
    ("gentileschi-lucretia", "卢克蕾提亚", "Lucretia Artemisia Gentileschi", "阿特米西娅·真蒂莱斯基", 1621, "巴洛克", "painting"),
    ("poussin-arcadia", "阿卡迪亚的牧人", "Et in Arcadia ego Poussin", "尼古拉·普桑", 1637, "巴洛克", "painting"),
    ("poussin-holy", "圣家庭", "Holy Family Poussin", "尼古拉·普桑", 1645, "巴洛克", "painting"),

    # ===================== 荷兰黄金时代 =====================
    ("girl-pearl", "戴珍珠耳环的少女", "Girl with a Pearl Earring Vermeer", "约翰内斯·维米尔", 1665, "荷兰黄金时代", "painting"),
    ("milkmaid", "倒牛奶的女仆", "The Milkmaid Vermeer", "约翰内斯·维米尔", 1658, "荷兰黄金时代", "painting"),
    ("view-delft", "代尔夫特风景", "View of Delft Vermeer", "约翰内斯·维米尔", 1661, "荷兰黄金时代", "painting"),
    ("music-lesson", "音乐课", "The Music Lesson Vermeer", "约翰内斯·维米尔", 1662, "荷兰黄金时代", "painting"),
    ("letter-vermeer", "情书", "The Love Letter Vermeer", "约翰内斯·维米尔", 1669, "荷兰黄金时代", "painting"),
    ("wine-glass", "酒杯", "The Wine Glass Vermeer", "约翰内斯·维米尔", 1659, "荷兰黄金时代", "painting"),
    ("laughing-girl", "微笑的女仆", "The Laughing Girl Vermeer", "约翰内斯·维米尔", 1659, "荷兰黄金时代", "painting"),
    ("allegory-painting", "绘画的艺术", "The Art of Painting Vermeer", "约翰内斯·维米尔", 1666, "荷兰黄金时代", "painting"),
    ("merry-company", "欢乐聚会", "Merry Company Hals", "弗兰斯·哈尔斯", 1620, "荷兰黄金时代", "painting"),
    ("laughing-cavalier", "微笑的骑士", "The Laughing Cavalier Hals", "弗兰斯·哈尔斯", 1624, "荷兰黄金时代", "painting"),
    ("gypsy-girl", "吉普赛女郎", "The Gypsy Girl Hals", "弗兰斯·哈尔斯", 1628, "荷兰黄金时代", "painting"),
    ("regents-almshouse", "养老院女管理员", "The Regents of the Old Men's Almshouse Hals", "弗兰斯·哈尔斯", 1664, "荷兰黄金时代", "painting"),
    ("stecn-eve", "快乐的酒徒", "The Merry Drinker Steen", "扬·斯特恩", 1660, "荷兰黄金时代", "painting"),
    ("stecn-feast", "圣尼古拉节", "The Feast of St. Nicolas Steen", "扬·斯特恩", 1660, "荷兰黄金时代", "painting"),
    ("terborch-letter", "读信的女子", "The Letter Ter Borch", "赫拉德·特博赫", 1660, "荷兰黄金时代", "painting"),
    ("de-witte-church", "教堂内部", "Interior of a Church de Witte", "伊曼纽·德·维特", 1660, "荷兰黄金时代", "painting"),
    ("cuyp-cows", "牛群", "Cattle Cuyp", "阿尔伯特·克伊普", 1650, "荷兰黄金时代", "painting"),
    ("hobbema-avenue", "林荫大道", "The Avenue at Middelharnis Hobbema", "梅因德特·霍贝玛", 1689, "荷兰黄金时代", "painting"),
    ("raucemacher", "静物与乐器", "Still Life with Musical Instruments", "威廉·卡尔夫", 1650, "荷兰黄金时代", "painting"),
    ("kalf-wine", "酒杯静物", "Still Life with a Nautilus Cup Kalf", "威廉·卡尔夫", 1650, "荷兰黄金时代", "painting"),
    ("vander-heyden", "街道", "The Straight Canal van der Heyden", "扬·范·德·海登", 1660, "荷兰黄金时代", "painting"),
    ("berchem-herd", "牧群", "Herdsmen Berchem", "克拉斯·贝尔赫姆", 1650, "荷兰黄金时代", "painting"),
    ("wouwerman-halt", "驿站", "The Halt Wouwerman", "菲利普·沃弗曼", 1655, "荷兰黄金时代", "painting"),
    ("potter-bull", "公牛", "The Young Bull Potter", "保罗·波特", 1647, "荷兰黄金时代", "painting"),

    # ===================== 洛可可 =====================
    ("watteau-pilgrimage", "西苔岛朝圣", "Pilgrimage to Cythera Watteau", "让-安托万·华托", 1717, "洛可可", "painting"),
    ("watteau-gilles", "吉尔", "Gilles Watteau", "让-安托万·华托", 1719, "洛可可", "painting"),
    ("watteau-fete", "游乐图", "Fête galante Watteau", "让-安托万·华托", 1715, "洛可可", "painting"),
    ("boucher-brunette", "黑发女仆", "The Brunette Boucher", "弗朗索瓦·布歇", 1750, "洛可可", "painting"),
    ("boucher-odalias", "澡后的狄安娜", "Diana at the Bath Boucher", "弗朗索瓦·布歇", 1742, "洛可可", "painting"),
    ("boucher-milliner", "女帽商", "The Milliner Boucher", "弗朗索瓦·布歇", 1746, "洛可可", "painting"),
    ("fragonard-swing", "秋千", "The Swing Fragonard", "让-奥诺雷·弗拉戈纳尔", 1767, "洛可可", "painting"),
    ("fragonard-stolen", "偷来的吻", "The Stolen Kiss Fragonard", "让-奥诺雷·弗拉戈纳尔", 1780, "洛可可", "painting"),
    ("fragonard-bathers", "沐浴者", "The Bathers Fragonard", "让-奥诺雷·弗拉戈纳尔", 1765, "洛可可", "painting"),
    ("lancret-repast", "舞会", "A Dance in the Country Lancret", "尼古拉·朗克雷", 1730, "洛可可", "painting"),
    ("pater-embarquement", "登船", "Embarkation Pater", "让-巴蒂斯特·帕特", 1720, "洛可可", "painting"),
    ("nattier-princess", "公主肖像", "Portrait of a Princess Nattier", "让-马克·纳捷", 1740, "洛可可", "painting"),
    ("vian-bath", "浴女", "The Bathers Vian", "卡尔·范·路", 1750, "洛可可", "painting"),
    ("chardin-grace", "餐前祈祷", "The Grace Chardin", "让-巴蒂斯特·西梅翁·夏尔丹", 1740, "洛可可", "painting"),

    # ===================== 新古典主义 =====================
    ("david-oath", "网球场宣誓", "The Tennis Court Oath David", "雅克-路易·大卫", 1791, "新古典主义", "painting"),
    ("david-horatii", "荷拉斯兄弟之誓", "Oath of the Horatii David", "雅克-路易·大卫", 1784, "新古典主义", "painting"),
    ("david-marat", "马拉之死", "The Death of Marat David", "雅克-路易·大卫", 1793, "新古典主义", "painting"),
    ("david-coronation", "拿破仑加冕", "The Coronation of Napoleon David", "雅克-路易·大卫", 1807, "新古典主义", "painting"),
    ("david-sabines", "萨宾妇女", "The Intervention of the Sabine Women David", "雅克-路易·大卫", 1799, "新古典主义", "painting"),
    ("david-psyche", "普赛克与丘比特", "Psyché et l'Amour David", "雅克-路易·大卫", 1817, "新古典主义", "painting"),
    ("ingres-bather", "泉", "The Source Ingres", "让-奥古斯特-多米尼克·安格尔", 1856, "新古典主义", "painting"),
    ("ingres-turkish", "土耳其浴室", "The Turkish Bath Ingres", "让-奥古斯特-多米尼克·安格尔", 1862, "新古典主义", "painting"),
    ("ingres-apotheosis", "荷马礼赞", "The Apotheosis of Homer Ingres", "让-奥古斯特-多米尼克·安格尔", 1827, "新古典主义", "painting"),
    ("ingres-odalisque", "大宫女", "Grande Odalisque Ingres", "让-奥古斯特-多米尼克·安格尔", 1814, "新古典主义", "painting"),
    ("ingres-vow", "路易十三的誓言", "The Vow of Louis XIII Ingres", "让-奥古斯特-多米尼克·安格尔", 1824, "新古典主义", "painting"),
    ("gerard-psyche", "普赛克", "Psyche receiving the first kiss of Love Gérard", "弗朗索瓦·热拉尔", 1798, "新古典主义", "painting"),
    ("guerin-aeneas", "埃涅阿斯叙述", "Aeneas tells Dido Girodet", "吉罗代", 1812, "新古典主义", "painting"),
    ("prudhon-josephine", "约瑟芬皇后", "Portrait of Empress Josephine Prud'hon", "皮埃尔-保罗·普吕东", 1805, "新古典主义", "painting"),
    ("benouville-roman", "罗马修道院", "The Roman Campagna Benouville", "莱昂·邦维尔", 1860, "新古典主义", "painting"),
    ("gerome-moor", "摩尔人沐浴", "Moorish Bath Gérôme", "让-莱昂·热罗姆", 1870, "新古典主义", "painting"),
    ("lepage-joan", "圣女贞德", "Joan of Arc Bastien-Lepage", "巴斯蒂安-勒帕热", 1879, "新古典主义", "painting"),
    ("cabanel-venus", "维纳斯的诞生", "The Birth of Venus Cabanel", "亚历山大·卡巴内尔", 1863, "新古典主义", "painting"),

    # ===================== 浪漫主义 =====================
    ("liberty", "自由引导人民", "Liberty Leading the People Delacroix", "欧仁·德拉克罗瓦", 1830, "浪漫主义", "painting"),
    ("wanderer-fog", "雾海上的旅人", "Wanderer above the Sea of Fog Friedrich", "卡斯帕·大卫·弗里德里希", 1818, "浪漫主义", "painting"),
    ("third-may", "1808年5月3日", "The Third of May Goya", "弗朗西斯科·戈雅", 1814, "浪漫主义", "painting"),
    ("hay-wain", "干草车", "The Hay Wain Constable", "约翰·康斯太勃尔", 1821, "浪漫主义", "painting"),
    ("fighting-temeraire", "被拖去解体的战舰无畏号", "The Fighting Temeraire Turner", "约瑟夫·透纳", 1839, "浪漫主义", "painting"),
    ("friedrich-abel", "山中的十字架", "The Cross in the Mountains Friedrich", "卡斯帕·大卫·弗里德里希", 1812, "浪漫主义", "painting"),
    ("friedrich-seaside", "海边修士", "The Monk by the Sea Friedrich", "卡斯帕·大卫·弗里德里希", 1810, "浪漫主义", "painting"),
    ("friedrich-snow", "雪中的修道院", "Abbey in the Oakwood Friedrich", "卡斯帕·大卫·弗里德里希", 1810, "浪漫主义", "painting"),
    ("friedrich-chalk", "白垩崖", "Chalk Cliffs on Rügen Friedrich", "卡斯帕·大卫·弗里德里希", 1818, "浪漫主义", "painting"),
    ("turner-snowstorm", "雪暴中的海船", "Snow Storm Turner", "约瑟夫·透纳", 1812, "浪漫主义", "painting"),
    ("turner-rain", "雨、蒸汽与速度", "Rain, Steam and Speed Turner", "约瑟夫·透纳", 1844, "浪漫主义", "painting"),
    ("turner-slave", "奴隶船", "The Slave Ship Turner", "约瑟夫·透纳", 1840, "浪漫主义", "painting"),
    ("constable-salisbury", "索尔兹伯里教堂", "Salisbury Cathedral Constable", "约翰·康斯太勃尔", 1823, "浪漫主义", "painting"),
    ("constable-dedham", "代德姆谷", "Dedham Vale Constable", "约翰·康斯太勃尔", 1802, "浪漫主义", "painting"),
    ("constable-flatford", "弗拉特福德磨坊", "Flatford Mill Constable", "约翰·康斯太勃尔", 1817, "浪漫主义", "painting"),
    ("goya-naked", "裸体的马哈", "La Maja Desnuda Goya", "弗朗西斯科·戈雅", 1797, "浪漫主义", "painting"),
    ("goya-clothed", "着衣的马哈", "La Maja Vestida Goya", "弗朗西斯科·戈雅", 1803, "浪漫主义", "painting"),
    ("goya-family", "查理四世一家", "The Family of Charles IV Goya", "弗朗西斯科·戈雅", 1800, "浪漫主义", "painting"),
    ("goya-shootings", "5月2日", "The Second of May Goya", "弗朗西斯科·戈雅", 1814, "浪漫主义", "painting"),
    ("goya-dogs", "吞食儿子的农神", "Saturn Devouring His Son Goya", "弗朗西斯科·戈雅", 1823, "浪漫主义", "painting"),
    ("delacroix-dante", "但丁之筏", "The Barque of Dante Delacroix", "欧仁·德拉克罗瓦", 1822, "浪漫主义", "painting"),
    ("delacroix-massacre", "希俄斯大屠杀", "The Massacre at Chios Delacroix", "欧仁·德拉克罗瓦", 1824, "浪漫主义", "painting"),
    ("delacroix-mlacz", "阿尔及尔妇女", "Women of Algiers Delacroix", "欧仁·德拉克罗瓦", 1834, "浪漫主义", "painting"),
    ("delacroix-lion", "狮猎", "The Lion Hunt Delacroix", "欧仁·德拉克罗瓦", 1861, "浪漫主义", "painting"),
    ("delacroix-ork", "花园里的犹太新娘", "Jewish Wedding Delacroix", "欧仁·德拉克罗瓦", 1839, "浪漫主义", "painting"),
    ("gericault-raft", "梅杜萨之筏", "The Raft of the Medusa Géricault", "泰奥多尔·席里科", 1819, "浪漫主义", "painting"),
    ("gericault-crazy", "疯女", "Portrait of a Woman Suffering from Obsession Géricault", "泰奥多尔·席里科", 1822, "浪漫主义", "painting"),
    ("blake-great", "伟大的红色龙", "The Great Red Dragon Blake", "威廉·布莱克", 1805, "浪漫主义", "painting"),
    ("blake-ancients", "古代", "The Ancient of Days Blake", "威廉·布莱克", 1794, "浪漫主义", "painting"),
    ("palmer-harvest", "月下收获", "The Harvest Moon Palmer", "塞缪尔·帕尔默", 1830, "浪漫主义", "painting"),
    ("friedrich-grief", "孤树", "Solitary Tree Friedrich", "卡斯帕·大卫·弗里德里希", 1822, "浪漫主义", "painting"),
    ("martin-pandaemonium", "潘得蒙尼乌姆", "Pandæmonium Martin", "约翰·马丁", 1841, "浪漫主义", "painting"),
    ("turner-calais", "加莱码头", "Calais Pier Turner", "约瑟夫·透纳", 1803, "浪漫主义", "painting"),

    # ===================== 拉斐尔前派 =====================
    ("ophelia", "奥菲莉亚", "Ophelia Millais", "约翰·埃弗里特·米莱", 1852, "拉斐尔前派", "painting"),
    ("woman-toilette", "梳妆的女子", "Woman at her Toilette Degas", "埃德加·德加", 1885, "印象派", "sketch"),
    ("millais-huguenot", "被赦免的胡格诺教徒", "A Huguenot Millais", "约翰·埃弗里特·米莱", 1852, "拉斐尔前派", "painting"),
    ("hunt-light", "世界之光", "The Light of the World Hunt", "威廉·霍尔曼·亨特", 1853, "拉斐尔前派", "painting"),
    ("hunt-shadow", "替罪羊", "The Scapegoat Hunt", "威廉·霍尔曼·亨特", 1856, "拉斐尔前派", "painting"),
    ("rossetti-beata", "贝亚特丽切", "Beata Beatrix Rossetti", "但丁·加布里埃尔·罗塞蒂", 1872, "拉斐尔前派", "painting"),
    ("rossetti-daydream", "白日梦", "The Day Dream Rossetti", "但丁·加布里埃尔·罗塞蒂", 1880, "拉斐尔前派", "painting"),
    ("burne-jones-golden", "金色的阶梯", "The Golden Stairs Burne-Jones", "爱德华·伯恩-琼斯", 1880, "拉斐尔前派", "painting"),
    ("burne-jones-king", "考费杜阿王与乞丐女", "King Cophetua and the Beggar Maid Burne-Jones", "爱德华·伯恩-琼斯", 1884, "拉斐尔前派", "painting"),
    ("waterhouse-shalott", "夏洛特夫人", "The Lady of Shalott Waterhouse", "约翰·威廉·沃特豪斯", 1888, "拉斐尔前派", "painting"),
    ("waterhouse-narcissus", "厄科与那喀索斯", "Echo and Narcissus Waterhouse", "约翰·威廉·沃特豪斯", 1903, "拉斐尔前派", "painting"),

    # ===================== 现实主义 =====================
    ("whistler-mother", "惠斯勒的母亲", "Whistler's Mother", "詹姆斯·惠斯勒", 1871, "现实主义", "painting"),
    ("olympia", "奥林匹亚", "Olympia Manet", "爱德华·马奈", 1863, "现实主义", "painting"),
    ("manet-lunch", "草地上的午餐", "Le Déjeuner sur l'herbe Manet", "爱德华·马奈", 1863, "现实主义", "painting"),
    ("manet-folies", "女神游乐厅的吧台", "A Bar at the Folies-Bergère Manet", "爱德华·马奈", 1882, "现实主义", "painting"),
    ("manet-emperor", "处决马克西米利安", "The Execution of Emperor Maximilian Manet", "爱德华·马奈", 1868, "现实主义", "painting"),
    ("manet-fifer", "吹笛少年", "The Fifer Manet", "爱德华·马奈", 1866, "现实主义", "painting"),
    ("courbet-stone", "采石工", "The Stone Breakers Courbet", "古斯塔夫·库尔贝", 1849, "现实主义", "painting"),
    ("courbet-origin", "奥尔南的葬礼", "A Burial at Ornans Courbet", "古斯塔夫·库尔贝", 1850, "现实主义", "painting"),
    ("courbet-studio", "画室", "The Painter's Studio Courbet", "古斯塔夫·库尔贝", 1855, "现实主义", "painting"),
    ("courbet-wave", "海浪", "The Wave Courbet", "古斯塔夫·库尔贝", 1870, "现实主义", "painting"),
    ("millet-gleaners", "拾穗者", "The Gleaners Millet", "让-弗朗索瓦·米勒", 1857, "现实主义", "painting"),
    ("millet-angelus", "晚祷", "The Angelus Millet", "让-弗朗索瓦·米勒", 1859, "现实主义", "painting"),
    ("millet-sower", "播种者", "The Sower Millet", "让-弗朗索瓦·米勒", 1850, "现实主义", "painting"),
    ("daumier-third", "三等车厢", "The Third-Class Carriage Daumier", "奥诺雷·杜米埃", 1864, "现实主义", "painting"),
    ("daumier-crispin", " Crispin 与 Scapin", "Crispin and Scapin Daumier", "奥诺雷·杜米埃", 1860, "现实主义", "painting"),
    ("tissot-parisienne", "巴黎女郎", "The Parisian Tissot", "詹姆斯·提索", 1870, "现实主义", "painting"),
    ("steer-bathers", " bathing", "Bathers at Bridport Steer", "菲利普·威尔逊·斯蒂尔", 1890, "现实主义", "painting"),
    ("homer-breezing", "微风", "Breezing Up Homer", "温斯洛·霍默", 1876, "现实主义", "painting"),
    ("homer-gulf", "墨西哥湾流", "The Gulf Stream Homer", "温斯洛·霍默", 1899, "现实主义", "painting"),
    ("eakins-clinic", "格罗斯诊所", "The Gross Clinic Eakins", "托马斯·埃金斯", 1875, "现实主义", "painting"),
    ("eakins-rowing", "单人划艇", "The Champion Single Sculls Eakins", "托马斯·埃金斯", 1871, "现实主义", "painting"),
    ("breton-angelus", "罢工", "The Strike Breton", "朱尔·布雷东", 1890, "现实主义", "painting"),

    # ===================== 印象派 =====================
    ("impression-sunrise", "印象·日出", "Impression Sunrise Monet", "克劳德·莫奈", 1872, "印象派", "painting"),
    ("water-lilies", "睡莲", "Water Lilies Monet", "克劳德·莫奈", 1906, "印象派", "painting"),
    ("monet-poppies", "罂粟花田", "Poppies Monet", "克劳德·莫奈", 1873, "印象派", "painting"),
    ("monet-rouen", "鲁昂大教堂", "Rouen Cathedral Monet", "克劳德·莫奈", 1894, "印象派", "painting"),
    ("monet-woman", "绿衣女人", "The Woman in the Green Dress Monet", "克劳德·莫奈", 1866, "印象派", "painting"),
    ("monet-garden", "吉维尼花园", "The Artist's Garden at Giverny Monet", "克劳德·莫奈", 1900, "印象派", "painting"),
    ("monet-japanese", "日本桥", "The Japanese Footbridge Monet", "克劳德·莫奈", 1899, "印象派", "painting"),
    ("monet-londres", "伦敦议会大厦", "Houses of Parliament Monet", "克劳德·莫奈", 1904, "印象派", "painting"),
    ("renoir-moulin", "煎饼磨坊的舞会", "Bal du moulin de la Galette Renoir", "皮埃尔-奥古斯特·雷诺阿", 1876, "印象派", "painting"),
    ("renoir-lunch", "船上的午宴", "Luncheon of the Boating Party Renoir", "皮埃尔-奥古斯特·雷诺阿", 1881, "印象派", "painting"),
    ("renoir-umbrellas", "雨伞", "The Umbrellas Renoir", "皮埃尔-奥古斯特·雷诺阿", 1885, "印象派", "painting"),
    ("renoir-gabrielle", "加布里埃尔", "Gabrielle Renoir", "皮埃尔-奥古斯特·雷诺阿", 1900, "印象派", "painting"),
    ("degas-rehearsal", "舞蹈课", "The Ballet Class Degas", "埃德加·德加", 1874, "印象派", "painting"),
    ("degas-star", "明星", "The Star Degas", "埃德加·德加", 1878, "印象派", "painting"),
    ("degas-absinthe", "苦艾酒", "L'Absinthe Degas", "埃德加·德加", 1876, "印象派", "painting"),
    ("degas-bath", "盆浴", "The Tub Degas", "埃德加·德加", 1886, "印象派", "painting"),
    ("degas-jockeys", "赛马", "Racehorses Degas", "埃德加·德加", 1880, "印象派", "painting"),
    ("pissarro-boulevard", "蒙马特大道", "Boulevard Montmartre Pissarro", "卡米耶·毕沙罗", 1897, "印象派", "painting"),
    ("pissarro-harvest", "收获", "The Harvest Pissarro", "卡米耶·毕沙罗", 1882, "印象派", "painting"),
    ("morisot-cradle", "摇篮", "The Cradle Morisot", "贝尔特·莫里索", 1872, "印象派", "painting"),
    ("morisot-sister", "妹妹", "The Sister Morisot", "贝尔特·莫里索", 1870, "印象派", "painting"),
    ("caillebotte-floor", "刨地板的人", "The Floor Scrapers Caillebotte", "古斯塔夫·卡耶博特", 1875, "印象派", "painting"),
    ("caillebotte-pont", "欧洲桥", "Le Pont de l'Europe Caillebotte", "古斯塔夫·卡耶博特", 1876, "印象派", "painting"),
    ("sisley-flood", "洪水", "The Flood at Port-Marly Sisley", "阿尔弗雷德·西斯莱", 1876, "印象派", "painting"),
    ("sisley-lane", "小路", "The Lane Sisley", "阿尔弗雷德·西斯莱", 1880, "印象派", "painting"),
    ("monet-woman2", "撑阳伞的女人", "Woman with a Parasol Monet", "克劳德·莫奈", 1875, "印象派", "painting"),
    ("renoir-swing", "秋千", "The Swing Renoir", "皮埃尔-奥古斯特·雷诺阿", 1876, "印象派", "painting"),
    ("monet-wild", "野生虞美人", "Wild Poppies Monet", "克劳德·莫奈", 1873, "印象派", "painting"),
    ("bazille-bathers", "浴者", "The Bathers Bazille", "弗雷德里克·巴齐耶", 1870, "印象派", "painting"),
    ("guillaumin-rails", "铁轨", "The Rails Guillaumin", "阿尔芒·吉约曼", 1870, "印象派", "painting"),
    ("liebermann-parrot", "鹦鹉女子", "Woman with Parrots Liebermann", "马克斯·利伯曼", 1873, "印象派", "painting"),
    ("cassatt-mother", "母与子", "Mother and Child Cassatt", "玛丽·卡萨特", 1890, "印象派", "painting"),
    ("monet-ice", "阿让特伊之冬", "The Magpie Monet", "克劳德·莫奈", 1869, "印象派", "painting"),
    ("renoir-concert", "音乐会", "The Concert Renoir", "皮埃尔-奥古斯特·雷诺阿", 1880, "印象派", "painting"),
    ("monet-gare", "圣拉扎尔车站", "La Gare Saint-Lazare Monet", "克劳德·莫奈", 1877, "印象派", "painting"),
    ("morisot-butterfly", "蝴蝶", "Butterfly Hunt Morisot", "贝尔特·莫里索", 1874, "印象派", "painting"),
    ("pissarro-place", "广场", "Place du Théâtre Français Pissarro", "卡米耶·毕沙罗", 1898, "印象派", "painting"),
    ("sisley-marly", "马尔港的洪水", "The Marly-le-Roi Sisley", "阿尔弗雷德·西斯莱", 1875, "印象派", "painting"),
    ("degas-cafe", "咖啡馆音乐会", "Café Concert Degas", "埃德加·德加", 1877, "印象派", "painting"),
    ("renoir-bather", "浴女", "Blonde Bather Renoir", "皮埃尔-奥古斯特·雷诺阿", 1887, "印象派", "painting"),
    ("monet-etoile", "帆船", "Sailboats Monet", "克劳德·莫奈", 1874, "印象派", "painting"),
    ("pissarro-ile", "红色屋顶", "Red Roofs Pissarro", "卡米耶·毕沙罗", 1877, "印象派", "painting"),

    # ===================== 后印象派 =====================
    ("starry-night", "星月夜", "The Starry Night Van Gogh", "文森特·梵高", 1889, "后印象派", "painting"),
    ("sunflowers", "向日葵", "Sunflowers Van Gogh", "文森特·梵高", 1888, "后印象派", "painting"),
    ("moulin-rouge", "红磨坊", "At the Moulin Rouge Lautrec", "亨利·德·图卢兹-劳特累克", 1895, "后印象派", "painting"),
    ("vangogh-bedroom", "阿尔勒的卧室", "Bedroom in Arles Van Gogh", "文森特·梵高", 1889, "后印象派", "painting"),
    ("vangogh-cafe", "夜间露天咖啡馆", "The Café Terrace on the Place du Forum Van Gogh", "文森特·梵高", 1888, "后印象派", "painting"),
    ("vangogh-irises", "鸢尾花", "Irises Van Gogh", "文森特·梵高", 1889, "后印象派", "painting"),
    ("vangogh-self", "自画像", "Self-Portrait Van Gogh", "文森特·梵高", 1889, "后印象派", "painting"),
    ("vangogh-crows", "麦田群鸦", "Wheatfield with Crows Van Gogh", "文森特·梵高", 1890, "后印象派", "painting"),
    ("vangogh-shoes", "旧鞋", "A Pair of Shoes Van Gogh", "文森特·梵高", 1887, "后印象派", "painting"),
    ("cezanne-cardplayers", "玩纸牌者", "The Card Players Cézanne", "保罗·塞尚", 1895, "后印象派", "painting"),
    ("cezanne-mountains", "圣维克多山", "Mont Sainte-Victoire Cézanne", "保罗·塞尚", 1900, "后印象派", "painting"),
    ("cezanne-apples", "苹果篮", "The Basket of Apples Cézanne", "保罗·塞尚", 1894, "后印象派", "painting"),
    ("cezanne-bather", "浴者", "The Bathers Cézanne", "保罗·塞尚", 1900, "后印象派", "painting"),
    ("cezanne-madame", "夫人肖像", "Madame Cézanne Cézanne", "保罗·塞尚", 1885, "后印象派", "painting"),
    ("gauguin-vision", "黄色基督", "The Yellow Christ Gauguin", "保罗·高更", 1889, "后印象派", "painting"),
    ("gauguin-spirit", "精灵在注视", "The Spirit of the Dead Watching Gauguin", "保罗·高更", 1892, "后印象派", "painting"),
    ("gauguin-tahiti", "我们来自何方", "Where Do We Come From Gauguin", "保罗·高更", 1897, "后印象派", "painting"),
    ("gauguin-arearea", "欢乐", "Arearea Gauguin", "保罗·高更", 1892, "后印象派", "painting"),
    ("seurat-bathers", "大碗岛的星期天", "A Sunday Afternoon on the Island of La Grande Jatte Seurat", "乔治·修拉", 1886, "后印象派", "painting"),
    ("seurat-circus", "马戏团", "The Circus Seurat", "乔治·修拉", 1891, "后印象派", "painting"),
    ("seurat-models", "模特", "The Models Seurat", "乔治·修拉", 1888, "后印象派", "painting"),
    ("signac-port", "港口", "The Port of Saint-Tropez Signac", "保罗·西涅克", 1901, "后印象派", "painting"),
    ("lautrec-divan", "沙发床", "The Sofa Lautrec", "亨利·德·图卢兹-劳特累克", 1894, "后印象派", "painting"),
    ("lautrec-salon", "沙龙", "In the Salon Lautrec", "亨利·德·图卢兹-劳特累克", 1890, "后印象派", "painting"),
    ("lautrec-ambassadeurs", "大使酒馆", "At the Ambassadeurs Lautrec", "亨利·德·图卢兹-劳特累克", 1877, "后印象派", "painting"),
    ("lautrec-troupe", "拉古吕", "La Goulue Lautrec", "亨利·德·图卢兹-劳特累克", 1891, "后印象派", "painting"),
    ("vangogh-postman", "邮差鲁兰", "Portrait of Armand Roulin Van Gogh", "文森特·梵高", 1888, "后印象派", "painting"),
    ("vangogh-zouave", "阿尔勒姑娘", "L'Arlésienne Van Gogh", "文森特·梵高", 1890, "后印象派", "painting"),
    ("vangogh-sunset", "夕阳下的柳树", "Willows at Sunset Van Gogh", "文森特·梵高", 1888, "后印象派", "painting"),
    ("cezanne-still", "静物与窗帘", "Still Life with Curtain Cézanne", "保罗·塞尚", 1895, "后印象派", "painting"),
    ("gauguin-bonjour", "布道后的幻象", "Vision After the Sermon Gauguin", "保罗·高更", 1888, "后印象派", "painting"),
    ("seurat-channel", "格兰德·让特角的黄昏", "The Channel of Gravelines Seurat", "乔治·修拉", 1890, "后印象派", "painting"),
    ("redon-cyclops", "独眼巨人", "The Cyclops Redon", "奥迪隆·雷东", 1898, "后印象派", "painting"),
    ("redon-buddha", " Buddha", "The Buddha Redon", "奥迪隆·雷东", 1904, "后印象派", "painting"),
    ("vangogh-roots", "树根", "Tree Roots Van Gogh", "文森特·梵高", 1890, "后印象派", "painting"),
    ("cezanne-jardin", "花园", "The Garden Cézanne", "保罗·塞尚", 1900, "后印象派", "painting"),
    ("gauguin-nevermore", "不再", "Nevermore Gauguin", "保罗·高更", 1897, "后印象派", "painting"),
    ("lautrec-woman", "梳头的女人", "The Toilette Lautrec", "亨利·德·图卢兹-劳特累克", 1896, "后印象派", "painting"),
    ("vangogh-harvest", "丰收", "The Harvest Van Gogh", "文森特·梵高", 1888, "后印象派", "painting"),
    ("cezanne-boy", "戴帽男孩", "Boy with a Straw Hat Cézanne", "保罗·塞尚", 1890, "后印象派", "painting"),

    # ===================== 象征主义 =====================
    ("moreau-galatea", "伽拉忒亚", "Galatea Moreau", "古斯塔夫·莫罗", 1880, "象征主义", "painting"),
    ("moreau-apparition", "显现", "The Apparition Moreau", "古斯塔夫·莫罗", 1876, "象征主义", "painting"),
    ("khnopff-caress", "抚爱", "Caress of the Sphinx Khnopff", "费尔南德·克诺普夫", 1896, "象征主义", "painting"),
    ("khnopff-belgique", "比利时", "Belgium Khnopff", "费尔南德·克诺普夫", 1888, "象征主义", "painting"),
    ("redon-closed", "闭上的眼睛", "The Closed Eyes Redon", "奥迪隆·雷东", 1890, "象征主义", "painting"),
    ("toorop-three", "三种信仰", "The Three Brides Toorop", "扬·托罗普", 1893, "象征主义", "painting"),
    ("vallotton-bath", "浴女", "The Bath Vallotton", "费利克斯·瓦洛东", 1893, "象征主义", "painting"),
    ("klimt-symbol", "音乐 II", "Music II Klimt", "古斯塔夫·克里姆特", 1915, "象征主义", "painting"),
    ("carriere-family", "家庭", "The Family Carrière", "欧仁·卡里埃", 1890, "象征主义", "painting"),
    ("serusier-talisman", "护符", "The Talisman Sérusier", "保罗·塞吕西耶", 1888, "象征主义", "painting"),

    # ===================== 维也纳分离派 =====================
    ("kiss-klimt", "吻", "The Kiss Klimt", "古斯塔夫·克里姆特", 1908, "维也纳分离派", "painting"),
    ("klimt-portrait-adele", "阿黛尔·布洛赫-鲍尔肖像", "Portrait of Adele Bloch-Bauer Klimt", "古斯塔夫·克里姆特", 1907, "维也纳分离派", "painting"),
    ("klimt-judith", "犹滴", "Judith Klimt", "古斯塔夫·克里姆特", 1901, "维也纳分离派", "painting"),
    ("klimt-tree", "生命之树", "Tree of Life Klimt", "古斯塔夫·克里姆特", 1909, "维也纳分离派", "painting"),
    ("klimt-beethoven", "贝多芬横饰带", "The Beethoven Frieze Klimt", "古斯塔夫·克里姆特", 1902, "维也纳分离派", "painting"),
    ("klimt-danae", "达那厄", "Danae Klimt", "古斯塔夫·克里姆特", 1907, "维也纳分离派", "painting"),
    ("kokoschka-bride", "风的新娘", "The Bride of the Wind Kokoschka", "奥斯卡·柯克西卡", 1914, "维也纳分离派", "painting"),
    ("moser-woman", "女性肖像", "Portrait of a Woman Moser", "科尔曼·莫泽", 1910, "维也纳分离派", "painting"),

    # ===================== 表现主义 =====================
    ("scream", "呐喊", "The Scream Munch", "爱德华·蒙克", 1893, "表现主义", "painting"),
    ("schiele-self", "带光环的自画像", "Egon Schiele self-portrait", "埃贡·席勒", 1912, "表现主义", "painting"),
    ("munch-madonna", "圣母", "Madonna Munch", "爱德华·蒙克", 1894, "表现主义", "painting"),
    ("munch-vampire", "吸血鬼", "Love and Pain Munch", "爱德华·蒙克", 1895, "表现主义", "painting"),
    ("munch-dance", "生命之舞", "The Dance of Life Munch", "爱德华·蒙克", 1900, "表现主义", "painting"),
    ("munch-sick", "病孩", "The Sick Child Munch", "爱德华·蒙克", 1885, "表现主义", "painting"),
    ("kirchner-street", "柏林街景", "Berlin Street Scene Kirchner", "恩斯特·路德维希·基希纳", 1913, "表现主义", "painting"),
    ("kirchner-bathers", "浴者", "Bathers Kirchner", "恩斯特·路德维希·基希纳", 1909, "表现主义", "painting"),
    ("nolde-last-supper", "最后的晚餐", "The Last Supper Nolde", "埃米尔·诺尔德", 1909, "表现主义", "painting"),
    ("nolde-masks", "面具", "Masks Nolde", "埃米尔·诺尔德", 1911, "表现主义", "painting"),
    ("dix-metropolis", "大都会", "Metropolis Dix", "奥托·迪克斯", 1928, "表现主义", "painting"),
    ("dix-trench", "战壕", "The Trench Dix", "奥托·迪克斯", 1923, "表现主义", "painting"),
    ("grosz-pillars", " pillars of society", "Pillars of Society Grosz", "乔治·格罗兹", 1926, "表现主义", "painting"),
    ("beckmann-night", "夜", "Night Beckmann", "马克斯·贝克曼", 1918, "表现主义", "painting"),
    ("marc-blue", "蓝马", "The Blue Horse Marc", "弗朗茨·马尔克", 1911, "表现主义", "painting"),
    ("marc-tower", "塔楼中的红牛", "The Red Bull Marc", "弗朗茨·马尔克", 1912, "表现主义", "painting"),
    ("jawlensky-spanish", "西班牙女子", "Spanish Woman Jawlensky", "阿列克谢·冯·亚夫伦斯基", 1913, "表现主义", "painting"),
    ("schmidt-rotluff-house", "房屋", "House Schmidt-Rottluff", "卡尔·施密特-罗特卢夫", 1910, "表现主义", "painting"),
    ("heimann-circus", "马戏团", "Circus Heymann", "爱达·海曼", 1920, "表现主义", "painting"),
    ("pechstein-fishing", "渔民", "Fishermen Pechstein", "马克斯·佩希斯坦", 1910, "表现主义", "painting"),
    ("muybridge", "运动中的人体", "Human Figure in Motion", "爱德华·迈布里奇", 1887, "表现主义", "sketch"),
    ("schiele-city", "小镇", "The Small City Schiele", "埃贡·席勒", 1913, "表现主义", "painting"),
    ("schiele-card", "（手）", "Hands Schiele", "埃贡·席勒", 1917, "表现主义", "sketch"),
    ("munch-ash", "灰烬", "Ashes Munch", "爱德华·蒙克", 1894, "表现主义", "painting"),
    ("kirchner-self", "自画像", "Self-Portrait as a Soldier Kirchner", "恩斯特·路德维希·基希纳", 1915, "表现主义", "painting"),
    ("nolde-garden", "鲜花花园", "Flowering Garden Nolde", "埃米尔·诺尔德", 1908, "表现主义", "painting"),

    # ===================== 野兽派 =====================
    ("matisse-dance", "舞蹈", "The Dance Matisse", "亨利·马蒂斯", 1910, "野兽派", "painting"),
    ("matisse-music", "音乐", "Music Matisse", "亨利·马蒂斯", 1910, "野兽派", "painting"),
    ("matisse-red", "红色画室", "The Red Studio Matisse", "亨利·马蒂斯", 1911, "野兽派", "painting"),
    ("matisse-joy", "生活的欢乐", "Le Bonheur de vivre Matisse", "亨利·马蒂斯", 1906, "野兽派", "painting"),
    ("matisse-woman", "戴帽子的女人", "Woman with a Hat Matisse", "亨利·马蒂斯", 1905, "野兽派", "painting"),
    ("matisse-snail", "蜗牛", "The Snail Matisse", "亨利·马蒂斯", 1953, "野兽派", "painting"),
    ("matisse-goldfish", "金鱼", "Goldfish Matisse", "亨利·马蒂斯", 1912, "野兽派", "painting"),
    ("derain-london", "伦敦桥", "Charing Cross Bridge Derain", "安德烈·德兰", 1906, "野兽派", "painting"),
    ("derain-collioure", "科利乌尔港", "The Port of Collioure Derain", "安德烈·德兰", 1905, "野兽派", "painting"),
    ("vlaminck-restaurant", "餐厅", "The Restaurant Vlaminck", "莫里斯·德·弗拉芒克", 1905, "野兽派", "painting"),
    ("marquet-port", "海边港口", "The Port Marquet", "阿尔贝·马尔凯", 1908, "野兽派", "painting"),
    ("friesz-harbor", "勒阿弗尔港", "The Harbor Friesz", "奥顿·弗里斯", 1906, "野兽派", "painting"),
    ("braque-large", "大裸女", "Grand Nu Braque", "乔治·布拉克", 1908, "野兽派", "painting"),
    ("valtat-poppy", "罂粟", "Poppy Field Valtat", "路易·瓦尔塔", 1900, "野兽派", "painting"),

    # ===================== 立体主义 =====================
    ("picasso-avignon", "亚维农的少女", "Les Demoiselles d'Avignon Picasso", "巴勃罗·毕加索", 1907, "立体主义", "painting"),
    ("picasso-guitar", "吉他", "Guitar Picasso", "巴勃罗·毕加索", 1912, "立体主义", "painting"),
    ("picasso-bottle", "瓶子与酒杯", "Bottle and Wine Glass Picasso", "巴勃罗·毕加索", 1912, "立体主义", "painting"),
    ("picasso-three", "三个音乐家", "Three Musicians Picasso", "巴勃罗·毕加索", 1921, "立体主义", "painting"),
    ("picasso-war", "格尔尼卡", "Guernica Picasso", "巴勃罗·毕加索", 1937, "立体主义", "painting"),
    ("picasso-dryad", "林中精灵", "The Dryad Picasso", "巴勃罗·毕加索", 1908, "立体主义", "painting"),
    ("braque-violin", "小提琴与烛台", "Violin and Candlestick Braque", "乔治·布拉克", 1910, "立体主义", "painting"),
    ("braque-mandora", "曼陀林", "Mandora Braque", "乔治·布拉克", 1909, "立体主义", "painting"),
    ("gris-breakfast", "早餐", "The Breakfast Gris", "胡安·格里斯", 1914, "立体主义", "painting"),
    ("gris-portrait", "毕加索肖像", "Portrait of Pablo Picasso Gris", "胡安·格里斯", 1912, "立体主义", "painting"),
    ("lec-fruit", "水果盘", "The Fruit Dish Léger", "费尔南·莱热", 1910, "立体主义", "painting"),
    ("lec-city", "城市", "The City Léger", "费尔南·莱热", 1919, "立体主义", "painting"),
    ("picasso-cry", "哭泣的女人", "Weeping Woman Picasso", "巴勃罗·毕加索", 1937, "立体主义", "painting"),
    ("picasso-self", "自画像", "Self-Portrait Picasso", "巴勃罗·毕加索", 1907, "立体主义", "painting"),
    ("braque-still", "静物与酒瓶", "Still Life with Bottles Braque", "乔治·布拉克", 1913, "立体主义", "painting"),
    ("picasso-rails", "藤椅", "Still Life with Chair Caning Picasso", "巴勃罗·毕加索", 1912, "立体主义", "painting"),
    ("gris-glass", "玻璃", "Glass Gris", "胡安·格里斯", 1915, "立体主义", "painting"),
    ("lec-mechanic", "机械师", "The Mechanic Léger", "费尔南·莱热", 1920, "立体主义", "painting"),

    # ===================== 未来主义 =====================
    ("boccioni-street", "街头噪声侵入房屋", "The Street Enters the House Boccioni", "翁贝托·波丘尼", 1911, "未来主义", "painting"),
    ("boccioni-movement", "空间中连续的独特形式", "Unique Forms of Continuity in Space Boccioni", "翁贝托·波丘尼", 1913, "未来主义", "painting"),
    ("boccioni-city", "城市的兴起", "The City Rises Boccioni", "翁贝托·波丘尼", 1910, "未来主义", "painting"),
    ("balla-dinamism", "系狗皮带的运动", "Dynamism of a Dog on a Leash Balla", "贾科莫·巴拉", 1912, "未来主义", "painting"),
    ("balla-child", "阳台上奔跑的孩子", "Abstract Speed Baller", "贾科莫·巴拉", 1913, "未来主义", "painting"),
    ("severini-pan", "潘潘舞", "The Pan-Pan Séverini", "吉诺·塞韦里尼", 1911, "未来主义", "painting"),
    ("carra-funeral", "葬礼", "The Funeral of the Anarchist Galli Carrà", "卡罗·卡拉", 1911, "未来主义", "painting"),
    ("russolo-revolt", "叛乱", "Revolt Russolo", "路易吉·鲁索洛", 1911, "未来主义", "painting"),

    # ===================== 至上/构成主义 =====================
    ("black-square", "黑方块", "Black Square Malevich", "卡济米尔·马列维奇", 1915, "至上主义", "painting"),
    ("malevich-red", "红方块", "Red Square Malevich", "卡济米尔·马列维奇", 1915, "至上主义", "painting"),
    ("malevich-white", "白上白", "Suprematist Composition White on White Malevich", "卡济米尔·马列维奇", 1918, "至上主义", "painting"),
    ("malevich-grain", "收获", "The Grain Harvests Malevich", "卡济米尔·马列维奇", 1911, "至上主义", "painting"),
    ("lissitzky-proun", "Proun", "Proun Lissitzky", "埃尔·利西茨基", 1920, "构成主义", "painting"),
    ("lissitzky-story", "用声音讲故事的人", "The Story of Two Squares Lissitzky", "埃尔·利西茨基", 1922, "构成主义", "painting"),
    ("tatlin-tower", "第三国际纪念碑", "Tatlin's Tower Tatlin", "弗拉基米尔·塔特林", 1920, "构成主义", "painting"),
    ("rodchenko-circles", "圆规", "Circles Rodchenko", "亚历山大·罗琴科", 1921, "构成主义", "painting"),
    ("popova-architectonic", "建筑构成", "Architectonic Composition Popova", "柳博芙·波波娃", 1918, "构成主义", "painting"),
    ("stepanova-figure", "人物构成", "Figure Composition Stepanova", "瓦尔瓦拉·斯捷潘诺娃", 1920, "构成主义", "painting"),

    # ===================== 新造型/包豪斯 =====================
    ("mondrian-comp", "红黄蓝构成", "Composition with Red Blue and Yellow Mondrian", "皮特·蒙德里安", 1930, "新造型主义", "painting"),
    ("mondrian-broadway", "百老汇爵士乐", "Broadway Boogie-Woogie Mondrian", "皮特·蒙德里安", 1943, "新造型主义", "painting"),
    ("mondrian-red", "红、蓝、黄构成", "Composition II with Red Blue and Yellow Mondrian", "皮特·蒙德里安", 1930, "新造型主义", "painting"),
    ("mondrian-gray", "灰树", "The Gray Tree Mondrian", "皮特·蒙德里安", 1911, "新造型主义", "painting"),
    ("kandinsky-archer", "几个圆圈", "Several Circles Kandinsky", "瓦西里·康定斯基", 1926, "抽象艺术", "painting"),

    # ===================== 抽象艺术（补充） =====================
    ("kandinsky-composition8", "第八号构成", "Composition VIII Kandinsky", "瓦西里·康定斯基", 1923, "抽象艺术", "painting"),
    ("kandinsky-yellow", "黄·红·蓝", "Yellow Red Blue Kandinsky", "瓦西里·康定斯基", 1925, "抽象艺术", "painting"),
    ("klee-senecio", "喜剧演员", "Senecio Klee", "保罗·克利", 1922, "抽象艺术", "painting"),
    ("klee-fish", "鱼类魔术", "Fish Magic Klee", "保罗·克利", 1925, "抽象艺术", "painting"),
    ("klee-castle", "城堡与太阳", "Castle and Sun Klee", "保罗·克利", 1928, "抽象艺术", "painting"),
    ("miro-mere-ubu", "乌布王之母", "Mère Ubu Miró", "胡安·米罗", 1929, "抽象艺术", "painting"),
    ("miro-birth", "世界的诞生", "The Birth of the World Miró", "胡安·米罗", 1925, "抽象艺术", "painting"),
    ("miro-construction", "耕作", "The Tilled Field Miró", "胡安·米罗", 1923, "抽象艺术", "painting"),
    ("delaunay-paris", "巴黎城", "The City of Paris Delaunay", "罗伯特·德劳内", 1910, "抽象艺术", "painting"),
    ("delaunay-windows", "同时的窗", "Simultaneous Windows Delaunay", "罗伯特·德劳内", 1912, "抽象艺术", "painting"),
    ("macke-hat", "黄帽女子", "Woman in a Yellow Hat Macke", "奥古斯特·马克", 1913, "抽象艺术", "painting"),
    ("jawlensky-spanish2", "西班牙女子肖像", "Spanish Woman Jawlensky", "阿列克谢·冯·亚夫伦斯基", 1913, "抽象艺术", "painting"),

    # ===================== 超现实主义 =====================
    ("persistence-memory", "记忆的永恒", "The Persistence of Memory Dalí", "萨尔瓦多·达利", 1931, "超现实主义", "painting"),
    ("dali-metamorphosis", "那喀索斯的变形", "Metamorphosis of Narcissus Dalí", "萨尔瓦多·达利", 1937, "超现实主义", "painting"),
    ("dali-dream", "梦境", "The Dream Dalí", "萨尔瓦多·达利", 1937, "超现实主义", "painting"),
    ("dali-masturbator", "伟大的自慰者", "The Great Masturbator Dalí", "萨尔瓦多·达利", 1929, "超现实主义", "painting"),
    ("magritte-son", "人类之子", "The Son of Man Magritte", "勒内·马格利特", 1964, "超现实主义", "painting"),
    ("magritte-treachery", "形象的叛逆", "The Treachery of Images Magritte", "勒内·马格利特", 1929, "超现实主义", "painting"),
    ("magritte-mirror", "假镜子", "The False Mirror Magritte", "勒内·马格利特", 1928, "超现实主义", "painting"),
    ("ernst-celebes", "大象西里伯斯", "The Elephant Celebes Ernst", "马克斯·恩斯特", 1921, "超现实主义", "painting"),
    ("ernst-robes", "新娘的修饰", "The Robing of the Bride Ernst", "马克斯·恩斯特", 1940, "超现实主义", "painting"),
    ("tanguy-mama", "妈妈，爸爸受伤了", "Mama, Papa is Wounded!", "伊夫·唐吉", 1927, "超现实主义", "painting"),
    ("delvaux-train", "夜车", "The Night Train Delvaux", "保罗·德尔沃", 1947, "超现实主义", "painting"),
    ("carrington-self", "自画像", "Self-Portrait Carrington", "利奥诺拉·卡林顿", 1938, "超现实主义", "painting"),
    ("tanning-night", "小夜曲", "Eine kleine Nachtmusik Tanning", "多萝西娅·坦宁", 1943, "超现实主义", "painting"),

    # ===================== 美国绘画 / 抽象表现主义 =====================
    ("hopper-nighthawks", "夜游者", "Nighthawks Hopper", "爱德华·霍普", 1942, "美国绘画", "painting"),
    ("hopper-office", "小城办公室", "Office in a Small City Hopper", "爱德华·霍普", 1953, "美国绘画", "painting"),
    ("okeeffe-canna", "红色美人蕉", "Red Canna O'Keeffe", "乔治亚·奥基芙", 1924, "美国绘画", "painting"),
    ("okeeffe-skull", "鹿头骨与白玫瑰", "Cow's Skull O'Keeffe", "乔治亚·奥基芙", 1931, "美国绘画", "painting"),
    ("pollock-one", "一号（1950）", "Number 1 Pollock", "杰克逊·波洛克", 1950, "抽象表现主义", "painting"),
    ("pollock-lavender", "薰衣草之雾", "Lavender Mist Pollock", "杰克逊·波洛克", 1950, "抽象表现主义", "painting"),
    ("rothko-maroon", "栗与黑", "Maroon Rothko", "马克·罗斯科", 1958, "抽象表现主义", "painting"),
    ("rothko-orange", "橙、红、黄", "Orange Red Yellow Rothko", "马克·罗斯科", 1961, "抽象表现主义", "painting"),
    ("dekooning-woman", "女人 I", "Woman I de Kooning", "威廉·德·库宁", 1952, "抽象表现主义", "painting"),
    ("kline-chief", "首领", "Chief Kline", "弗朗茨·克莱恩", 1950, "抽象表现主义", "painting"),
    ("johns-flag", "国旗", "Flag Johns", "贾斯珀·约翰斯", 1955, "新达达", "painting"),
    ("rauschenberg-bed", "床", "Bed Rauschenberg", "罗伯特·劳森伯格", 1955, "新达达", "painting"),
    ("wood-american", "美国哥特式", "American Gothic Wood", "格兰特·伍德", 1930, "地方主义", "painting"),
    ("wyeth-christina", "克里斯蒂娜的世界", "Christina's World Wyeth", "安德鲁·怀斯", 1948, "地方主义", "painting"),
    ("sargent-madame", "X 夫人", "Madame X Sargent", "约翰·辛格·萨金特", 1884, "美国绘画", "painting"),
    ("whistler-nocturne", "夜曲：蓝与金", "Nocturne Whistler", "詹姆斯·惠斯勒", 1875, "美国绘画", "painting"),

    # ===================== 浮世绘 / 朴素艺术（补全 44 原图中的东方与素描） =====================
    ("great-wave", "神奈川冲浪里", "The Great Wave Hokusai", "葛饰北斋", 1831, "浮世绘", "painting"),
    ("hokusai-fuji", "凯风快晴", "Fine Wind Hokusai", "葛饰北斋", 1832, "浮世绘", "painting"),
    ("hokusai-waterfall", "瀑布", "Hokusai Waterfall", "葛饰北斋", 1832, "浮世绘", "painting"),
    ("hiroshige-rain", "大桥骤雨", "Sudden Shower Hiroshige", "歌川广重", 1857, "浮世绘", "painting"),
    ("hiroshige-tokaido", "东海道五十三次", "The Fifty-three Stations Hiroshige", "歌川广重", 1833, "浮世绘", "painting"),
    ("utamaro-beauty", "宽政三美人", "Utamaro Beauty", "喜多川歌麿", 1790, "浮世绘", "painting"),
    ("sleeping-gypsy", "沉睡的吉普赛人", "The Sleeping Gypsy Rousseau", "亨利·卢梭", 1897, "朴素艺术", "painting"),
    ("rousseau-snake", "蛇之诱惑", "The Snake Charmer Rousseau", "亨利·卢梭", 1907, "朴素艺术", "painting"),
    ("rousseau-dream", "梦", "The Dream Rousseau", "亨利·卢梭", 1910, "朴素艺术", "painting"),
    ("vitruvian", "维特鲁威人", "Vitruvian Man", "列奥纳多·达·芬奇", 1490, "文艺复兴", "sketch"),
    ("libyan-sibyl", "利比亚女巫研究", "Libyan Sibyl", "米开朗基罗", 1511, "文艺复兴", "sketch"),
    ("anatomical-shoulder", "肩部解剖研究", "Anatomical studies of the shoulder", "列奥纳多·达·芬奇", 1510, "文艺复兴", "sketch"),
    ("study-hands", "手的研究", "Studies of hands", "列奥纳多·达·芬奇", 1474, "文艺复兴", "sketch"),
    ("american-gothic2", "美国哥特式（素描）", "American Gothic study", "格兰特·伍德", 1930, "地方主义", "sketch"),
]

def build():
    items = []
    seen = set()
    for row in ART:
        if len(row) < 7:
            print("WARN malformed:", row)
            continue
        aid, zh, en, artist, year, movement, typ = row[0], row[1], row[2], row[3], row[4], row[5], row[6]
        if aid in seen:
            print("WARN duplicate id skipped:", aid)
            continue
        seen.add(aid)
        items.append({
            "id": aid,
            "title": zh,
            "artist": artist,
            "year": year,
            "movement": movement,
            "type": typ,
            "en": en,
            "wm": KNOWN_WM.get(aid),
        })
    return items

if __name__ == "__main__":
    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.abspath(os.path.join(here, "..", "draftgen", "static", "art-manifest.json"))
    items = build()
    import json as _json
    with open(out, "w", encoding="utf-8") as f:
        _json.dump(items, f, ensure_ascii=False, indent=1)
    print("Wrote", len(items), "items ->", out)
